server:
  port: 8009

spring:
  application:
    name: cloud-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.6.11:8848


service-url:
  nacos-user-service: http://cloud-payment-service
