server:
  port: 8060

spring:
  application:
    name: consul-consumer-payment
  cloud:
    consul:
      host: 192.168.6.11
      port: 8500
      discovery:
        service-name: ${spring.application.name}
