server:
  port: 8401

spring:
  application:
    name: cloud-ali-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.6.11:8848
    sentinel:
      transport:
        dashboard: 192.168.6.11:8080
        port: 8719


management:
  endpoints:
    web:
      exposure:
        include: '*'